---

- name: Generating an HTML report
  gather_facts: false
  hosts: all
  become: yes
  tasks:

    - name: Gather the facts
      ios_facts:
      register: all_facts

    - name: Create HTML report
      template:
        src: iosReport.j2
        dest: "/etc/ansible/DeviceReport/inventory_report.html"
      delegate_to: localhost
      run_once: true
